services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      # target: build-env
    image: identity-server
    ports:
      - 8080:8080
  db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: <YourStrong@Passw0rd>
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '<YourStrong@Passw0rd>' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
