volumes:
  sql1data:
    driver: local

services:
  identityprovider:
    image: ${DOCKER_REGISTRY-}identityprovider
    build:
      context: .
      dockerfile: IdentityProvider/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__EcAuthDbContext: "Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true"
      STATE_PASSWORD: ${STATE_PASSWORD:-strong_password_string_of_at_least_32_characters}
      GOOGLE_OAUTH2_APP_NAME: ${GOOGLE_OAUTH2_APP_NAME}
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      GOOGLE_OAUTH2_DISCOVERY_URL: ${GOOGLE_OAUTH2_DISCOVERY_URL}
      AMAZON_OAUTH2_APP_NAME: ${AMAZON_OAUTH2_APP_NAME}
      AMAZON_OAUTH2_CLIENT_ID: ${AMAZON_OAUTH2_CLIENT_ID}
      AMAZON_OAUTH2_CLIENT_SECRET: ${AMAZON_OAUTH2_CLIENT_SECRET}
      AMAZON_OAUTH2_AUTHORIZATION_ENDPOINT: ${AMAZON_OAUTH2_AUTHORIZATION_ENDPOINT}
      AMAZON_OAUTH2_TOKEN_ENDPOINT: ${AMAZON_OAUTH2_TOKEN_ENDPOINT}
      AMAZON_OAUTH2_USERINFO_ENDPOINT: ${AMAZON_OAUTH2_USERINFO_ENDPOINT}
      DEFAULT_ORGANIZATION_CODE: ${DEFAULT_ORGANIZATION_CODE}
      DEFAULT_ORGANIZATION_TENANT_NAME: ${DEFAULT_ORGANIZATION_TENANT_NAME}
  db:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sql1data:/var/opt/mssql
      - ./docker/db/backup:/var/opt/mssql/backup
    ports:
      - 1433:1433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U ${DB_USER} -P '${DB_PASSWORD}' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    # volumes:

    #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '<YourStrong@Passw0rd>' -d master -i /docker-entrypoint-initdb.d/init.sql"

  # マイグレーション用のサービス
  # 事前に `dotnet ef migrations bundle -f --output publish/bundle` で bundle を作成しておく
  # migration:
  #   build:
  #     context: .
  #     dockerfile: IdentityProvider/Dockerfile
  #   depends_on:
  #     - db
  #   environment:
  #     ConnectionStrings__EcAuthDbContext: "Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true"

  mockopenidprovider:
    image: ${DOCKER_REGISTRY-}mockopenidprovider
    build:
      context: .
      dockerfile: MockOpenIdProvider/Dockerfile
    environment:
      ConnectionStrings__MockIdpDbContext: "Server=${DB_HOST};Database=MockIdp;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true"
