// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockOpenIdProvider.Models;

#nullable disable

namespace MockOpenIdProvider.Migrations
{
    [DbContext(typeof(IdpDbContext))]
    [Migration("20250205154305_RenameAccessToken")]
    partial class RenameAccessToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MockOpenIdProvider.Models.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_in");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("access_token");
                });

            modelBuilder.Entity("MockOpenIdProvider.Models.AuthorizationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires_in");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER")
                        .HasColumnName("used");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("authorization_code");
                });

            modelBuilder.Entity("MockOpenIdProvider.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_secret");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("private_key");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("public_key");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("redirect_uri");

                    b.HasKey("Id");

                    b.ToTable("client");
                });

            modelBuilder.Entity("MockOpenIdProvider.Models.AccessToken", b =>
                {
                    b.HasOne("MockOpenIdProvider.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MockOpenIdProvider.Models.AuthorizationCode", b =>
                {
                    b.HasOne("MockOpenIdProvider.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
