name: .NET Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./EcAuth.sln

    - name: Build
      working-directory: ./IdpUtilities.Test
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./IdpUtilities.Test
      run: dotnet test --no-build --verbosity normal

    - name: Build
      working-directory: ./MockOpenIdProvider.Test
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./MockOpenIdProvider.Test
      run: dotnet test --no-build --verbosity normal

    - name: Build
      working-directory: ./IdentityProvider.Test
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./IdentityProvider.Test
      run: dotnet test --no-build --verbosity normal
