name: Playwright E2E Tests - IdentityProvider

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: <YourStrong@Passw0rd>

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: ${{ env.DB_PASSWORD }}
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: cat .env.dist >> $GITHUB_ENV
      - run: echo "DB_HOST=localhost" >> $GITHUB_ENV
      - run: echo "ConnectionStrings__EcAuthDbContext=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true" >> $GITHUB_ENV
      - run: echo "ConnectionStrings__MockIdpDbContext=Server=${DB_HOST};Database=${MOCK_IDP_DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=true;MultipleActiveResultSets=true" >> $GITHUB_ENV
      - run: echo "FEDERATE_OAUTH2_CLIENT_ID=${MOCK_IDP_FEDERATE_CLIENT_ID}" >> $GITHUB_ENV
      - run: echo "FEDERATE_OAUTH2_CLIENT_SECRET=${MOCK_IDP_FEDERATE_CLIENT_SECRET}" >> $GITHUB_ENV
      - run: echo "FEDERATE_OAUTH2_TOKEN_ENDPOINT=http://mockopenidprovider:8080/token" >> $GITHUB_ENV
      - run: echo "FEDERATE_OAUTH2_USERINFO_ENDPOINT=http://mockopenidprovider:8080/userinfo" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore ./EcAuth.sln

      - name: Build IdentityProvider
        run: dotnet build --no-restore --configuration Release IdentityProvider

      - name: Build MockOpenIdProvider
        run: dotnet build --no-restore --configuration Release MockOpenIdProvider
      - name: Migrate IdentityProvider DB
        working-directory: IdentityProvider
        run: dotnet ef database update

      - name: Migrate MockOpenIdProvider DB
        working-directory: MockOpenIdProvider
        run: dotnet ef database update

      - name: Start MockOpenIdProvider
        run: |
          export ASPNETCORE_HTTPS_PORT=9091
          export ASPNETCORE_URLS="https://0.0.0.0:9091"
          dotnet run --project MockOpenIdProvider --configuration Release --urls "https://0.0.0.0:9091" &
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Start IdentityProvider
        run: |
          export ASPNETCORE_HTTPS_PORT=8081
          export ASPNETCORE_URLS="https://0.0.0.0:8081"
          dotnet run --project IdentityProvider --configuration Release --urls "https://0.0.0.0:8081" &
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install Playwright
        working-directory: E2ETests
        run: |
          yarn install --frozen-lockfile
          yarn playwright install --with-deps chromium

      - name: Run Playwright E2E Tests
        working-directory: E2ETests
        run: yarn playwright test
